spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: test   
  application: 
      name: microservicecloud-config-atguigu-test
---
spring:
  profiles: dev   
  application: 
      name: microservicecloud-config-atguigu-dev
